### ISSUE TITLE
cashu requires python-bitcoinlib which makes extension unusable in LNbits

### ISSUE THREAD

**Issue by prusnak** [lnbits/cashu#44]
Transfered from https://github.com/lnbits/lnbits/pull/2044 here

----

Currently cashu extension is broken in LNbits, because it requires `python-bitcoinlib` which is not imported (not present in LNbits `pyproject.toml`). 

Relevant code that uses `python-bitcoinlib` is here: https://github.com/lnbits/cashu/blob/0.3.0/lib/cashu/core/script.py#L9-L18

We can either:
1) rewrite the code to use [embit](https://github.com/diybitcoinhardware/embit) instead of python-bitcoinlib (embed is imported by LNbits by default because other 3 dependencies need it)
2) copy required code from python-bitcoinlib to cashu repo (what boltz extension does with [boltz_client](https://github.com/lnbits/boltz/tree/main/boltz_client) dependency)
3) identify whether the code in `lib/cashu/core/script.py` is needed in LNbits context and if not, fix it so it's not imported there

**Comment by callebtc** [comment]
Fixed by #45 (removed python-bitcoinlib)
